### ISSUE TITLE
How to overwrite?

### ISSUE THREAD

**Issue by gonnavis** [Yuriy-Svetlov/compress-images#44]
If set INPUT and OUTPUT the same folder, will log
```
-------------
null
true
undefined
-------------
```
error: null, complete: true, statistic: undefined.
But the image file does not change.

**Comment by semiromid** [comment]
@gonnavis 
You can use 
```
compress_force (type:boolean): Force compress images already compressed images true or false;
```

Is not recommended to compress images in the same folder.

**Comment by gonnavis** [comment]
Thanks!

**Comment by TanyaScales** [comment]
@gonnavis - Did this work for you? I tried to use the compress_force: true as specified above with the same input an output path and I'm getting an error for PNG/JPGs:

For jpg:
```
err: Error: Command failed: <pathtomyproject>/node_modules/mozjpeg/vendor/cjpeg -quality 60 -outfile src/images/imagename.jpg src/images/imagename.jpg
  Empty input file
```

For png:
```
err: Error: Command failed: <pathtomyproject>/node_modules/pngquant-bin/vendor/pngquant --quality=20-50 -o src/images/template-previews/filename.png src/images/template-previews/filename.png
error: 'src/images/template-previews/vitality.png' exists; not overwriting
```

Curious if it worked for you as laid out.

**Comment by semiromid** [comment]
@TanyaScales 
Hi!

Download compress-images 1.9.4


And as example you may use:


```
    const 
    compress_images = require('compress-images'),
    fs = require('fs'),
    INPUT_path_to_your_images = 'src/img/**/!(*-min).png',
    OUTPUT_path = 'src/img/';
    
    compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: true, statistic: false, autoupdate: true}, false,
                                                {jpg: {engine: false, command: false}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50', '--ext=-min.png', '--force']}},
                                                {svg: {engine: false, command: false}},
                                                {gif: {engine: false, command: false}}, function(err, completed, statistic){
        if(err === null){
              fs.unlink(statistic.input, (err) => {
                    if (err) throw err;
                    console.log('successfully compressed and deleted '+statistic.input);
              });
        }
    });
```

**Comment by invinciblemuffi** [comment]
> @TanyaScales
> @gonnavis
> Hi!
> 
> Download compress-images 1.9.4
> 
> And as example you may use:
> 
> ```
>     const 
>     compress_images = require('compress-images'),
>     fs = require('fs'),
>     INPUT_path_to_your_images = 'src/img/**/!(*-min).png',
>     OUTPUT_path = 'src/img/';
>     
>     compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: true, statistic: false, autoupdate: true}, false,
>                                                 {jpg: {engine: false, command: false}},
>                                                 {png: {engine: 'pngquant', command: ['--quality=20-50', '--ext=-min.png', '--force']}},
>                                                 {svg: {engine: false, command: false}},
>                                                 {gif: {engine: false, command: false}}, function(err, completed, statistic){
>         if(err === null){
>               fs.unlink(statistic.input, (err) => {
>                     if (err) throw err;
>                     console.log('successfully compressed and deleted '+statistic.input);
>               });
>         }
>     });
> ```

As per the docs this solution only works for png images, for jpeg it does not work, firstly it says engine not defined, after defining mozjpeg engine it does not compress the image in same folder, I see original image size only.

**Comment by KoichaDev** [comment]
> > @TanyaScales
> > @gonnavis
> > Hi!
> > Download compress-images 1.9.4
> > And as example you may use:
> > ```
> >     const 
> >     compress_images = require('compress-images'),
> >     fs = require('fs'),
> >     INPUT_path_to_your_images = 'src/img/**/!(*-min).png',
> >     OUTPUT_path = 'src/img/';
> >     
> >     compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: true, statistic: false, autoupdate: true}, false,
> >                                                 {jpg: {engine: false, command: false}},
> >                                                 {png: {engine: 'pngquant', command: ['--quality=20-50', '--ext=-min.png', '--force']}},
> >                                                 {svg: {engine: false, command: false}},
> >                                                 {gif: {engine: false, command: false}}, function(err, completed, statistic){
> >         if(err === null){
> >               fs.unlink(statistic.input, (err) => {
> >                     if (err) throw err;
> >                     console.log('successfully compressed and deleted '+statistic.input);
> >               });
> >         }
> >     });
> > ```
> 
> As per the docs this solution only works for png images, for jpeg it does not work, firstly it says engine not defined, after defining mozjpeg engine it does not compress the image in same folder, I see original image size only.


Has anyone manged to get this to work? I'm just getting an error that says:

```
-----------------------------------
 File from: src/img/image.jpg
 File to: src/img/image.jpg
 Compression algorithm: [mozjpeg]
Error: Command failed: C:\Users\khoii\Local Sites\wp-starter-theme\app\public\wp-content\themes\_theme_name\node_modules\mozjpeg\vendor\cjpeg.exe -quality 60 -outfile src/img/image.jpg src/img/image.jpg
Empty input file

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {        
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\khoii\\Local Sites\\wp-starter-theme\\app\\public\\wp-content\\themes\\_theme_name\\node_modules\\mozjpeg\\vendor\\cjpeg.exe -quality 60 -outfile src/img/image.jpg src/img/image.jpg'
}
 [Error] Your file was not compressed!!!
 [Error] You can see log to:
-----------------------------------
Successfully compressed: true
C:\Users\khoii\Local Sites\wp-starter-theme\app\public\wp-content\themes\_theme_name\node_modules\compress-images\index.js:1452
                    if (err) throw err;
                             ^

[Error: EPERM: operation not permitted, open 'C:\2021-2-25 14.57.24 (857).txt'] {     
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\2021-2-25 14.57.24 (857).txt'
}
```

Here is my code:

```
const fs = require('fs');
const compress_images = require('compress-images');
const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';
const OUTPUT_path = 'src/img/';

compress_images(
  INPUT_path_to_your_images,
  OUTPUT_path,
  { compress_force: true, statistic: true, autoupdate: true, pathLog: '' },
  false,
  { jpg: { engine: 'mozjpeg', command: ['-quality', '60'] } },
  { png: { engine: 'pngquant', command: ['--quality=20-50', '--ext=-min.png', '--force'] } },
  { svg: { engine: 'svgo', command: '--multipass' } },
  { gif: { engine: 'gifsicle', command: ['--colors', '64', '--use-col=web'] } },
  function (err, completed, statistic) {
    if (err === null) {
      fs.unlink(statistic.input, (err) => {
        if (err) throw err;
        console.log('successfully compressed and deleted ' + statistic.input);
      });
    }

    console.log(`Successfully compressed: ${completed}`);
  }
);

```

**Comment by semiromid** [comment]
Hi @KoichaDev  !

This function only works with 'pngquant'. 
You tried compressing the ".jpg" image and you get the error.

Unfortunately, I don't have time to implement this for all engines yet.

**Comment by KoichaDev** [comment]
Ah, no wonder! It would be very nice if you have time to implement for all engines in near future! Thanks for replying me back @semiromid! :)

**Comment by semiromid** [comment]
@KoichaDev 

You need to specify a different folder

As example:

`const OUTPUT_path = 'build/img/';`

**Comment by semiromid** [comment]
@KoichaDev 

You are welcome. )

**Comment by KoichaDev** [comment]
I actually did that. I had to write a custom JS code that image(s) outputs on a temporary folder and then moving all the image files that have been compressed back to the original image src folder.

**Comment by semiromid** [comment]
@KoichaDev 

I recommend you rename your compressed images, for example add the prefix .min. And look for images to be compressed using a regular expression.

As example:
`const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';`

This is for performance.

**Comment by KoichaDev** [comment]
performance as compiling, or performance as speed performance on the website?

**Comment by semiromid** [comment]
@KoichaDev 

Performance when searching for uncompressed images. Unless, of course, you are compressing images one at a time.

**Comment by KoichaDev** [comment]
Thank you for sharing this insight! :)

**Comment by semiromid** [comment]
@KoichaDev 
You are welcome! 
Have a nice day and good work! )
