### ISSUE TITLE
tell me to install a additional module

### ISSUE THREAD

**Issue by pedrojotaa** [Yuriy-Svetlov/compress-images#64]
ERROR on screen "You must install additional module [npm install pngquant-bin --save]!
It does not work properly on some OS! If you will get an error try use other module"

**Comment by Yuriy-Svetlov** [comment]
@pedrojotaa Hello!

You need try to do  `npm install pngquant-bin --save`

**Comment by Yuriy-Svetlov** [comment]
> For pngquant - ['--quality=20-50', '-o'] If you want to compress in the same folder, as example: ['--quality=20-50', '--ext=.png', '--force']. To use this library you need to install it manually. It does not work properly on some OS (Win 7 x32 and maybe other). npm install pngquant-bin --save Quality should be in format min-max where min and max are numbers in range 0-100. Can be problems with cyrillic filename issues/317 In details: pngquant and pngquant-bin - wrapper

**Comment by Yuriy-Svetlov** [comment]
[See](https://github.com/Yuriy-Svetlov/compress-images#api)

**Comment by pedrojotaa** [comment]
const sharp = require('sharp')
const compress_images = require('compress-images')

let path = process.argv[2]

let width = Number(process.argv[3])

function resize(inputPath, outputPath, width){
    sharp(inputPath).resize({width: width}).toFile(outputPath, (error) => {
        if(error){
            console.log(error)
        }else{
            console.log('Arquivo redimensionado com sucesso!')
            compress(outputPath, './compress/')
        }
    })
}

function compress(inputPath, outputPath){
    compress_images(inputPath, outputPath, { compress_force: false, statistic: true, autoupdate: true }, false,
        { jpg: { engine: "mozjpeg", command: ["-quality", "60"] } },
        { png: { engine: "pngquant", command: ["--quality=20-50", "-o"] } },
        { svg: { engine: "svgo", command: "--multipass" } },
        { gif: { engine: "gifsicle", command: ["--colors", "64", "--use-col=web"] } },
    )
}

resize(path,'./temp/output_resize.jpg', width)

look, im resizing the img an after compress

**Comment by pedrojotaa** [comment]
https://imgur.com/TyHeIPm

look this img, im resizing and compress the image

**Comment by pedrojotaa** [comment]
when i try compress, show this error

**Comment by Yuriy-Svetlov** [comment]
@pedrojotaa Did you do `npm install pngquant-bin --save`?
